# Generated by Django 6.0.5 on 2026-05-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
