# Generated by Django 6.0.5 on 2026-05-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_time_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', '-is_featured', '-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Main cover image for service', null=True, upload_to='services/covers/'),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display on services page'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description for service detail page'),
        ),
        migrations.AddField(
            model_name='service',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of gallery image URLs'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description for service cards (max 150 words)'),
        ),
    ]
