# Generated by Django 6.0.5 on 2026-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_service_options_remove_service_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Customer's phone number", max_length=20)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('pre-wedding', 'Pre-Wedding'), ('portrait', 'Portrait'), ('commercial', 'Commercial'), ('baby-shower', 'Baby Shower'), ('birthday', 'Birthday'), ('other', 'Other')], default='wedding', help_text='Type of photography service inquiry', max_length=50)),
                ('preferred_date', models.DateField(blank=True, help_text="Customer's preferred event date", null=True)),
                ('location', models.CharField(blank=True, help_text='Event location or preferred shooting location', max_length=200)),
                ('message', models.TextField(help_text="Customer's detailed inquiry message")),
                ('admin_reply', models.TextField(blank=True, help_text="Admin's reply to the customer")),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', help_text='Current status of the inquiry', max_length=20)),
                ('is_replied', models.BooleanField(default=False, help_text='Whether admin has replied to this inquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
