# Generated by Django 6.0.5 on 2026-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='is_replied',
            new_name='replied',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'The Legacy (Wedding)'), ('pre-wedding', 'Pre-Wedding'), ('portrait', 'The Editorial (Portrait)'), ('commercial', 'The Visionary (Commercial)'), ('baby-shower', 'Baby Shower'), ('birthday', 'Birthday'), ('other', 'Other')], default='wedding', help_text='Type of photography service inquiry', max_length=50),
        ),
    ]
