# Generated by Django 6.0.5 on 2026-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_full_name_inquiry_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-is_featured', 'display_order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='order',
            new_name='display_order',
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reelcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
