# Generated by Django 6.0.5 on 2026-05-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this date is available for booking')),
                ('is_blocked_by_admin', models.BooleanField(default=False, help_text='Whether this date was manually blocked by admin')),
                ('reason', models.TextField(blank=True, help_text="Reason for blocking (e.g., 'Wedding Shoot', 'Personal Leave')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'ordering': ['date'],
            },
        ),
    ]
