# Generated by Django 6.0.5 on 2026-05-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Gallery Category', 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-is_featured', 'display_order', '-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='reelcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Reel Category', 'verbose_name_plural': 'Reel Categories'},
        ),
        migrations.AlterModelOptions(
            name='reelvideo',
            options={'ordering': ['-is_featured', 'display_order', '-created_at'], 'verbose_name': 'Reel Video', 'verbose_name_plural': 'Reel Videos'},
        ),
        migrations.RenameField(
            model_name='reelvideo',
            old_name='order',
            new_name='display_order',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='reelcategory',
            name='order',
        ),
    ]
