# Generated by Django 6.0.5 on 2026-05-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_gallerycategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='gallery/projects/')),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.gallerycategory')),
            ],
        ),
    ]
