# Generated by Django 6.0.5 on 2026-05-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_galleryproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='main.gallerycategory'),
        ),
        migrations.AlterModelOptions(
            name='galleryproject',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Gallery Project', 'verbose_name_plural': 'Gallery Projects'},
        ),
        migrations.RenameField(
            model_name='galleryproject',
            old_name='caption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for the category', null=True, upload_to='gallery/categories/covers/'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark category as featured'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galleryproject',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryproject',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryproject',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryproject',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='galleryproject',
            name='shoot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='galleryproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ReelCategory',
        ),
    ]
