# Generated by Django 6.0.5 on 2026-05-15 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_reelvideo_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reel Category',
                'verbose_name_plural': 'Reel Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-is_featured', 'order', '-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='galleryproject',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reelvideo',
            options={'ordering': ['-is_featured', 'order', '-created_at'], 'verbose_name': 'Reel Video', 'verbose_name_plural': 'Reel Videos'},
        ),
        migrations.RenameField(
            model_name='galleryproject',
            old_name='description',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='reelvideo',
            old_name='display_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='galleryproject',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='galleryproject',
            name='location',
        ),
        migrations.RemoveField(
            model_name='galleryproject',
            name='shoot_date',
        ),
        migrations.RemoveField(
            model_name='galleryproject',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class, e.g., 'fa-heart'", max_length=50),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='client_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reelvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='main.reelcategory'),
        ),
    ]
