# Generated by Django 6.0.5 on 2026-06-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_inquiry_status_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='Hello! I am your AI concierge. How can I help you today?', help_text='Welcome message displayed when user opens chatbot')),
                ('system_prompt', models.TextField(default='You are a helpful photography assistant for Dhrumil Bajak Photography.', help_text='System prompt for the AI model')),
                ('faq_items', models.JSONField(blank=True, default=list, help_text='FAQ items as JSON: [{"q": "Question", "a": "Answer"}, ...]')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable chatbot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='919106093868', help_text='WhatsApp business number (with country code, no + or spaces)', max_length=20)),
                ('message_template', models.TextField(default="Hi! I'm inquiring about a {service} session. Est: {price}.", help_text='Message template for WhatsApp quotes. Use {service} and {price} placeholders')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable WhatsApp contact option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice identifier (e.g., INV-2026-001)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice total amount', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('overdue', 'Overdue')], default='unpaid', help_text='Payment status', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF invoice file', null=True, upload_to='invoices/pdfs/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or terms')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date when payment was received', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='Associated booking', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='main.booking')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-generated_at'],
            },
        ),
    ]
