# Generated by Django 6.0.5 on 2026-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_chatbotconfiguration_whatsappconfiguration_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('welcome_message', models.TextField()),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
