# Generated by Django 6.0.5 on 2026-06-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_aiconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIConfiguration',
        ),
    ]
