# Generated by Django 5.2.4 on 2026-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_aiconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Common question asked by users', max_length=255)),
                ('answer', models.TextField(help_text='The answer the AI should provide')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which FAQs might be displayed or prioritized')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this FAQ for the AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot FAQ',
                'verbose_name_plural': 'Chatbot FAQs',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text="e.g., 'Cancellation Policy', 'Locations'", max_length=150)),
                ('content', models.TextField(help_text='Detailed information the chatbot should know')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this knowledge for the AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Knowledge',
                'verbose_name_plural': 'Chatbot Knowledge',
                'ordering': ['-created_at'],
            },
        ),
    ]
