# Generated by Django 5.2.4 on 2026-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_chatbotfaq_chatbotknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=150)),
                ('preferred_date', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
