# Generated by Django 5.2.4 on 2026-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='fallback_message',
            field=models.TextField(default='I apologize, I am having trouble connecting right now. Please try again or contact us on WhatsApp.', help_text='Message displayed when AI is offline or encounters an error'),
        ),
    ]
