# Generated by Django 5.2.4 on 2026-09-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_chatbotconfiguration_fallback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='availability_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to check calendar availability'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='human_handoff_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to handoff complex questions to human agent'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='inquiry_creation_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to automatically create Inquiry records'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='lead_qualification_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to collect lead information'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='package_recommendation_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to recommend packages'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='portfolio_recommendation_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to recommend gallery portfolios'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='pricing_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to quote pricing'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='service_recommendation_enabled',
            field=models.BooleanField(default=True, help_text='Allow AI to recommend specific services'),
        ),
    ]
