# Generated by Django 5.2.4 on 2026-10-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_chatbotconfiguration_availability_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom total amount for this booking. If left blank, service price is used.', max_digits=10, null=True),
        ),
    ]
